apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: mynamespace
  labels:
    role: api
    env: demo
spec:
  replicas: 1
  strategy:          #for updating image versions.
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: ismail55/backend:v4
        imagePullPolicy: IfNotPresent
        command: ["node", "server.js"]
        ports:
        - containerPort: 4000
        env:
          - name: PORT
            value: "4000"
          - name: MONGO_CONN_STR
            valueFrom:
              configMapKeyRef:
                name: mongodb-config
                key: MONGO_CONN_STR            # e.g mongodb://mongodb-svc:27017/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: password
        resources:
          requests: 
            cpu: "100m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
             path: /ready
             port: 4000
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
