apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: mynamespace
  labels:
    role: api
    env: demo
spec:
  replicas: 1
  strategy:          #for updating image versions.
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: ismail55/backend:v3
        imagePullPolicy: Always
        env:
          - name: MONGO_CONN_STR
            valueFrom:
              configMapKeyRef:
                name: mongodb-config
                key: MONGO_CONN_STR            # e.g mongodb://mongodb-svc:27017/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secrets
                key: password
        ports:
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /ok
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
             path: /ok
             port: 4000
          initialDelaySeconds: 10
          periodSeconds: 15
          successThreshold: 1
