---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mynamespace
spec:
  ports:
    name: http
    port: 80
  - port: 3000
    nodePort: 30953
    protocol: TCP
  type: NodePort
  selector:
   role: frontend
