apiVersion: v1
kind: Service
metadata:
  namespace: mynamespace
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb-service
    protocol: TCP
    port: 27017
    targetPort: 27017
